apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prod-project
  namespace: argocd
spec:
  description: Production environment project

  # Allow deployments to production namespace only
  destinations:
    - namespace: production
      server: https://kubernetes.default.svc

  # Only allow main repo for production
  sourceRepos:
    - 'https://github.com/barsukov/k8s-gitops-demo.git'

  # Limited cluster-scoped resources for production safety
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace

  # Allow standard namespaced resources
  namespaceResourceWhitelist:
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Secret
    - group: ''
      kind: Service
    - group: apps
      kind: Deployment
    - group: apps
      kind: ReplicaSet

  # Orphaned resources monitoring
  orphanedResources:
    warn: true
